[uwsgi]
chdir = /home/apps/kode-wilayah/src/api
module = app:app
master = true
processes = 4

socket = /run/uwsgi/kode_wilayah.sock
chown-socket = www-data:www-data
chmod-socket = 660
vacuum = true
die-on-term = true

# --- Environment Variables (Ganti os.getenv) ---
env = DB_HOST=127.0.0.1
env = DB_PORT=3306
env = DB_USER=kode_wilayah
env = DB_PASSWORD=K6FNYQ42%%ry1Ym
env = DB_NAME=kode_wilayah
env = SECRET_KEY=kunci-rahasia-anda-disini
env = STAGE_RUNNING=production #Hapus tanda # untuk set ke production, defaultnya development

# Lokasi log untuk debugging jika ada error
logto = /var/log/uwsgi/kode_wilayah.log